export const GET_COMMENTS = "GET_COMMENTS";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const GET_COMMENTS_BY_PRODUCT_ID = "GET_COMMENTS_BY_PRODUCT_ID";